apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: java-springboot
  namespace: rhn-support-tshearon
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: tbs-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-springboot
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: java-springboot-
      labels:
        build.appstudio.openshift.io/application: tbs-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-springboot
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: rhn-support-tshearon
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-java-springboot-basic.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:rhn-support-tshearon-java-springboot-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:05062775336d3f8efa9eb75357af8a6bd376fa57
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: java-springboot/$(tt.params.git-revision)
    status: {}
status: {}
